# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Local-Windows 

stages:
- stage: GitHub-db-ronaldo-correa-CI
  pool: Local-Windows
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files from GitHub to Pipeline staging folder'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\db-ronaldo-correa.dacpac'
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

- stage: New-release-db-ronaldo-correa-CD
  pool: CIT-326-Winter-2021-MSSQL2019-Development
  steps:
  - task: SqlDacpacDeploymentOnMachineGroup@0
    displayName: 'Deploy using : dacpac db-ronaldo-correa'
    inputs:
      DacpacFile: '$(System.DefaultWorkingDirectory)/_GitHub-db-ronaldo-correa-CI/drop/db-ronaldo-correa.dacpac'
      DatabaseName: 'db-ronaldo-correa'
      AuthScheme: sqlServerAuthentication
      SqlUsername: sa
      SqlPassword: '$(sql-dev-password)'
