# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Local-Windows 

stages:
- stage: CI
  pool: Local-Windows
  jobs:
  - job: 'Copyfiles' 
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files from GitHub to Pipeline staging folder'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**\db-ronaldo-correa.dacpac'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

- stage: CD
  pool: local-windows
  jobs:
  - job: 'deploysql'
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
         buildType: current
         downloadType: single
         downloadPath: $(System.DefaultWorkingDirectory)
         artifactName: 'drop'

      - task: SqlDacpacDeploymentOnMachineGroup@0
        displayName: 'Deploy using : dacpac db-ronaldo-correa'
        inputs:
          DacpacFile: '$(System.DefaultWorkingDirectory)/drop/db-ronaldo-correa.dacpac'
          DatabaseName: 'db-ronaldo-correa'
          AuthScheme: sqlServerAuthentication
          SqlUsername: 'sa'
          SqlPassword: '$(sql-dev-password)'
